# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('three_letters_code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
                ('manufacturer', models.CharField(max_length=50)),
                ('aircraft_model', models.CharField(max_length=50)),
                ('nb_rows_of_seats', models.PositiveIntegerField()),
                ('nb_col_of_seats', models.PositiveIntegerField()),
            ],
        ),
    ]
