# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10)),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Arrival')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Departure')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='plane',
            name='nb_col_of_seats',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='plane',
            name='nb_rows_of_seats',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flight.Person')),
            ],
            bases=('flight.person',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flight.Person')),
                ('salary', models.PositiveIntegerField()),
                ('job', models.CharField(max_length=100)),
            ],
            bases=('flight.person',),
        ),
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Plane'),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Flight'),
        ),
        migrations.CreateModel(
            name='AirCrew',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flight.Employee')),
                ('total_flying_hours', models.PositiveIntegerField()),
            ],
            bases=('flight.employee',),
        ),
        migrations.AddField(
            model_name='customer',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.Booking'),
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('aircrew_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flight.AirCrew')),
                ('license_number', models.CharField(max_length=100)),
            ],
            bases=('flight.aircrew',),
        ),
        migrations.AddField(
            model_name='departure',
            name='aircrew_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrew_1', to='flight.AirCrew'),
        ),
        migrations.AddField(
            model_name='departure',
            name='aircrew_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aircrew_2', to='flight.AirCrew'),
        ),
        migrations.AddField(
            model_name='departure',
            name='pilot_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_1', to='flight.Pilot'),
        ),
        migrations.AddField(
            model_name='departure',
            name='pilot_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_2', to='flight.Pilot'),
        ),
    ]
