# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-13 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20180111_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
