# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-18 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0008_auto_20180117_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='arrival',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flight.Arrival'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flight.Departure'),
        ),
    ]
